export const carouselSlides = [
    {
        id: 1,
        name: 'porsche',
        image: 'porsche-911gt3rs',
        desc: 'Porsche 911 GT3 RS',
        origin: 'german'
    },
    {
        id: 2,
        name: 'lamborghini',
        image: 'lamborghini-aventador',
        desc: 'Lamborghini Aventador',
        origin: 'italian'
    },
    {
        id: 3,
        name: 'mercedes',
        image: 'mercedes-gts',
        desc: 'Mercedes-AMG GTS',
        origin: 'german'
    },
    {
        id: 4,
        name: 'ferrari',
        image: 'ferrari-f60',
        desc: 'Ferrari F60 America',
        origin: 'italian'
    },
    {
        id: 5,
        name: 'tesla',
        image: 'tesla-model3',
        desc: 'Tesla Model 3',
        origin: 'american'
    }
];

export const catalogueCars = [
    {
        id: 1,
        company: 'Porsche',
        model: '911 GT3 RS',
        image: 'porsche-911gt3rs.png',
        color: 'red',
        seats: '2',
        rating: '5',
        transmission: 'manual',
        price: '150',
    },
    {
        id: 2,
        company: 'Tesla',
        model: 'Model 3',
        image: 'tesla-model3.png',
        color: 'grey',
        seats: '4',
        rating: '4.2',
        transmission: 'automatic',
        price: '60',
    },
    {
        id: 3,
        company: 'Ferrari',
        model: 'F60 America',
        image: 'ferrari-f60.png',
        color: 'blue',
        seats: '2',
        rating: '4.9',
        transmission: 'automatic',
        price: '210',
    },
    {
        id: 4,
        company: 'Aston Martin',
        model: 'DBS Superleggera',
        image: 'astonmartin-dbssuperleggera.png',
        color: 'silver',
        seats: '2',
        rating: '4.6',
        transmission: 'manual',
        price: '90',
    },
    {
        id: 5,
        company: 'Bugatti',
        model: 'Veyron',
        image: 'bugatti-veyron.png',
        color: 'white',
        seats: '2',
        rating: '4.7',
        transmission: 'manual',
        price: '240',
    },
    {
        id: 6,
        company: 'Lamborghini',
        model: 'Aventador',
        image: 'lamborghini-aventador.png',
        color: 'red',
        seats: '2',
        rating: '4.8',
        transmission: 'automatic',
        price: '120',
    },
    {
        id: 7,
        company: 'Bugatti',
        model: 'Chiron',
        image: 'bugatti-chiron.png',
        color: 'blue',
        seats: '2',
        rating: '5',
        transmission: 'automatic',
        price: '320',
    },
    {
        id: 8,
        company: 'Aston Martin',
        model: 'Vanquish',
        image: 'astonmartin-vanquish.png',
        color: 'green',
        seats: '2',
        rating: '4.4',
        transmission: 'automatic',
        price: '80',
    },
    {
        id: 9,
        company: 'Mercedes-AMG',
        model: 'GTS',
        image: 'mercedes-gts.png',
        color: 'yellow',
        seats: '2',
        rating: '4.2',
        transmission: 'automatic',
        price: '70',
    },
    {
        id: 10,
        company: 'BMW',
        model: 'M4',
        image: 'bmw-m4.png',
        color: 'silver',
        seats: '4',
        rating: '4.4',
        transmission: 'automatic',
        price: '70',
    },
    {
        id: 11,
        company: 'Ford',
        model: 'Mustang',
        image: 'ford-mustang.png',
        color: 'yellow',
        seats: '2',
        rating: '4.2',
        transmission: 'automatic',
        price: '80',
    },
    {
        id: 12,
        company: 'Dodge',
        model: 'Charger',
        image: 'dodge-charger.png',
        color: 'red',
        seats: '4',
        rating: '4.4',
        transmission: 'automatic',
        price: '90',
    }
]